### ISSUE TITLE
babel 插件应该如何配置？

### ISSUE THREAD

**Issue by zhuyuanmin** [jsx-plus/jsx-plus#1]
这些 babel 插件如何配置在 .babelrc 中？
{
  "presets": [],
  "plugins": [
    "babel-runtime-jsx-plus",
    "babel-plugin-transform-jsx-list",
    "babel-plugin-transform-jsx-condition",
    "babel-plugin-transform-jsx-memo",
    "babel-plugin-transform-jsx-slot",
    "babel-plugin-transform-jsx-class"
}

error =>  .babelrc  " was expected to return a function but returned "undefined"

注释掉 // "babel-runtime-jsx-plus",
当使用 jsx+ 属性的时候又报如下错误：
error => node_modules\babel-plugin-transform-jsx-condition\lib\index.js  "t.jsxExpressionContainer is not a function"

How to play ?

**Comment by wssgcg1213** [comment]
参考 babel 使用文档, 另外后面一个问题可以升级babel-core到最新版本
